export const SSE_EVENT_CHANNEL = 'SSE_EVENT_CHANNEL';
export const SSE_ERROR_EVENT = 'SSE_ERROR_EVENT';
export const ATTENDANCE_UPDATE_EVENT = 'ATTENDANCE_UPDATE_EVENT';
export const VISITOR_UPDATE_EVENT = 'VISITOR_UPDATE_EVENT';
