export const ApplicationConstants = {
  ATRegenerateExecutionTimeWindow: 3000,
  DEFAULT_UNBLOCK_INTERVAL_IN_MINS: 5,
  SUCCESS_STR: 'Success',
  ERROR_STR: 'Error',
  PROFILE_IMAGE_VERSION: '_1',
  PROFILE_IMAGE_FOLDER: 'plab_profile_image/',
  STRING: 'string',
  OBJECT_STR: 'object',
  MESSAGE_STR: 'message',
  ALPHABETS_REGEX: "^[A-Za-z\\s'-]+$",
  ALPHANUMERICS_REGEX: "^[A-Za-z0-9\\s'-]+$",
  SEPARATOR_SYMBOL: ':-',
  CODE_STR: 'code',
  S3_FILE_SEPARATOR_KEY: 'amazonaws.com/',
  PROD_ENVIRONMENT_KEY: 'prod',
  DEV_ENVIRONMENT_KEY: 'dev',
  PROFILE_IMAGE_BUCKET: 'profile_image',
  PROFILE_IMAGE_MIME: 'image',
  TRUE: 'true',
  FALSE: 'false',
  COMMENT_MAX_LENGTH: 100,
  IS_ACTIVE_KEY: 'isActive',

  REPORT_TYPE_CSV: 'csv',
  REPORT_TYPE_XLSX: 'xlsx',
  REPORT_TYPE_PDF: 'pdf',
};
