export const countryData = [
  {
    country: 'Afghanistan',
    countryCode: 'AF',
    currencyCode: 'AFN',
    currencySign: '؋',
    callingCode: '93',
    flag: '🇦🇫',
  },
  {
    country: 'Albania',
    countryCode: 'AL',
    currencyCode: 'ALL',
    currencySign: 'L',
    callingCode: '355',
    flag: '🇦🇱',
  },
  {
    country: 'Algeria',
    countryCode: 'DZ',
    currencyCode: 'DZD',
    currencySign: 'د.ج',
    callingCode: '213',
    flag: '🇩🇿',
  },
  {
    country: 'Andorra',
    countryCode: 'AD',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '376',
    flag: '🇦🇩',
  },
  {
    country: 'Angola',
    countryCode: 'AO',
    currencyCode: 'AOA',
    currencySign: 'Kz',
    callingCode: '244',
    flag: '🇦🇴',
  },
  {
    country: 'Antigua and Barbuda',
    countryCode: 'AG',
    currencyCode: 'XCD',
    currencySign: '$',
    callingCode: '1-268',
    flag: '🇦🇬',
  },
  {
    country: 'Argentina',
    countryCode: 'AR',
    currencyCode: 'ARS',
    currencySign: '$',
    callingCode: '54',
    flag: '🇦🇷',
  },
  {
    country: 'Armenia',
    countryCode: 'AM',
    currencyCode: 'AMD',
    currencySign: '֏',
    callingCode: '374',
    flag: '🇦🇲',
  },
  {
    country: 'Aruba',
    countryCode: 'AW',
    currencyCode: 'AWG',
    currencySign: 'ƒ',
    callingCode: '297',
    flag: '🇦🇼',
  },
  {
    country: 'Australia',
    countryCode: 'AU',
    currencyCode: 'AUD',
    currencySign: '$',
    callingCode: '61',
    flag: '🇦🇺',
  },
  {
    country: 'Austria',
    countryCode: 'AT',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '43',
    flag: '🇦🇹',
  },
  {
    country: 'Azerbaijan',
    countryCode: 'AZ',
    currencyCode: 'AZN',
    currencySign: '₼',
    callingCode: '994',
    flag: '🇦🇿',
  },
  {
    country: 'Bahamas',
    countryCode: 'BS',
    currencyCode: 'BSD',
    currencySign: '$',
    callingCode: '1-242',
    flag: '🇧🇸',
  },
  {
    country: 'Bahrain',
    countryCode: 'BH',
    currencyCode: 'BHD',
    currencySign: '.د.ب',
    callingCode: '973',
    flag: '🇧🇭',
  },
  {
    country: 'Bangladesh',
    countryCode: 'BD',
    currencyCode: 'BDT',
    currencySign: '৳',
    callingCode: '880',
    flag: '🇧🇩',
  },
  {
    country: 'Barbados',
    countryCode: 'BB',
    currencyCode: 'BBD',
    currencySign: '$',
    callingCode: '1-246',
    flag: '🇧🇧',
  },
  {
    country: 'Belarus',
    countryCode: 'BY',
    currencyCode: 'BYN',
    currencySign: 'Br',
    callingCode: '375',
    flag: '🇧🇾',
  },
  {
    country: 'Belgium',
    countryCode: 'BE',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '32',
    flag: '🇧🇪',
  },
  {
    country: 'Belize',
    countryCode: 'BZ',
    currencyCode: 'BZD',
    currencySign: '$',
    callingCode: '501',
    flag: '🇧🇿',
  },
  {
    country: 'Benin',
    countryCode: 'BJ',
    currencyCode: 'XOF',
    currencySign: 'Fr',
    callingCode: '229',
    flag: '🇧🇯',
  },
  {
    country: 'Bermuda',
    countryCode: 'BM',
    currencyCode: 'BMD',
    currencySign: '$',
    callingCode: '1-441',
    flag: '🇧🇲',
  },
  {
    country: 'Bhutan',
    countryCode: 'BT',
    currencyCode: 'BTN',
    currencySign: 'Nu.',
    callingCode: '975',
    flag: '🇧🇹',
  },
  {
    country: 'Bolivia',
    countryCode: 'BO',
    currencyCode: 'BOB',
    currencySign: 'Bs.',
    callingCode: '591',
    flag: '🇧🇴',
  },
  {
    country: 'Bosnia and Herzegovina',
    countryCode: 'BA',
    currencyCode: 'BAM',
    currencySign: 'KM',
    callingCode: '387',
    flag: '🇧🇦',
  },
  {
    country: 'Botswana',
    countryCode: 'BW',
    currencyCode: 'BWP',
    currencySign: 'P',
    callingCode: '267',
    flag: '🇧🇼',
  },
  {
    country: 'Brazil',
    countryCode: 'BR',
    currencyCode: 'BRL',
    currencySign: 'R$',
    callingCode: '55',
    flag: '🇧🇷',
  },
  {
    country: 'Brunei',
    countryCode: 'BN',
    currencyCode: 'BND',
    currencySign: '$',
    callingCode: '673',
    flag: '🇧🇳',
  },
  {
    country: 'Bulgaria',
    countryCode: 'BG',
    currencyCode: 'BGN',
    currencySign: 'лв',
    callingCode: '359',
    flag: '🇧🇬',
  },
  {
    country: 'Burkina Faso',
    countryCode: 'BF',
    currencyCode: 'XOF',
    currencySign: 'Fr',
    callingCode: '226',
    flag: '🇧🇫',
  },
  {
    country: 'Burundi',
    countryCode: 'BI',
    currencyCode: 'BIF',
    currencySign: 'Fr',
    callingCode: '257',
    flag: '🇧🇮',
  },
  {
    country: 'Cabo Verde',
    countryCode: 'CV',
    currencyCode: 'CVE',
    currencySign: 'Esc',
    callingCode: '238',
    flag: '🇨🇻',
  },
  {
    country: 'Cambodia',
    countryCode: 'KH',
    currencyCode: 'KHR',
    currencySign: '៛',
    callingCode: '855',
    flag: '🇰🇭',
  },
  {
    country: 'Cameroon',
    countryCode: 'CM',
    currencyCode: 'XAF',
    currencySign: 'Fr',
    callingCode: '237',
    flag: '🇨🇲',
  },
  {
    country: 'Canada',
    countryCode: 'CA',
    currencyCode: 'CAD',
    currencySign: '$',
    callingCode: '1',
    flag: '🇨🇦',
  },
  {
    country: 'Cayman Islands',
    countryCode: 'KY',
    currencyCode: 'KYD',
    currencySign: '$',
    callingCode: '1-345',
    flag: '🇰🇾',
  },
  {
    country: 'Central African Republic',
    countryCode: 'CF',
    currencyCode: 'XAF',
    currencySign: 'Fr',
    callingCode: '236',
    flag: '🇨🇫',
  },
  {
    country: 'Chad',
    countryCode: 'TD',
    currencyCode: 'XAF',
    currencySign: 'Fr',
    callingCode: '235',
    flag: '🇹🇩',
  },
  {
    country: 'Chile',
    countryCode: 'CL',
    currencyCode: 'CLP',
    currencySign: '$',
    callingCode: '56',
    flag: '🇨🇱',
  },
  {
    country: 'China',
    countryCode: 'CN',
    currencyCode: 'CNY',
    currencySign: '¥',
    callingCode: '86',
    flag: '🇨🇳',
  },
  {
    country: 'Colombia',
    countryCode: 'CO',
    currencyCode: 'COP',
    currencySign: '$',
    callingCode: '57',
    flag: '🇨🇴',
  },
  {
    country: 'Comoros',
    countryCode: 'KM',
    currencyCode: 'KMF',
    currencySign: 'Fr',
    callingCode: '269',
    flag: '🇰🇲',
  },
  {
    country: 'Comoros',
    countryCode: 'KM',
    currencyCode: 'KMF',
    currencySign: 'Fr',
    callingCode: '269',
    flag: '🇰🇲',
  },
  {
    country: 'Congo, Democratic Republic of the',
    countryCode: 'CD',
    currencyCode: 'CDF',
    currencySign: 'Fr',
    callingCode: '243',
    flag: '🇨🇩',
  },
  {
    country: 'Congo, Republic of the',
    countryCode: 'CG',
    currencyCode: 'XAF',
    currencySign: 'Fr',
    callingCode: '242',
    flag: '🇨🇬',
  },
  {
    country: 'Costa Rica',
    countryCode: 'CR',
    currencyCode: 'CRC',
    currencySign: '₡',
    callingCode: '506',
    flag: '🇨🇷',
  },
  {
    country: 'Croatia',
    countryCode: 'HR',
    currencyCode: 'HRK',
    currencySign: 'kn',
    callingCode: '385',
    flag: '🇭🇷',
  },
  {
    country: 'Cuba',
    countryCode: 'CU',
    currencyCode: 'CUP',
    currencySign: '₱',
    callingCode: '53',
    flag: '🇨🇺',
  },
  {
    country: 'Cyprus',
    countryCode: 'CY',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '357',
    flag: '🇨🇾',
  },
  {
    country: 'Czech Republic',
    countryCode: 'CZ',
    currencyCode: 'CZK',
    currencySign: 'Kč',
    callingCode: '420',
    flag: '🇨🇿',
  },
  {
    country: 'Denmark',
    countryCode: 'DK',
    currencyCode: 'DKK',
    currencySign: 'kr',
    callingCode: '45',
    flag: '🇩🇰',
  },
  {
    country: 'Djibouti',
    countryCode: 'DJ',
    currencyCode: 'DJF',
    currencySign: 'Fr',
    callingCode: '253',
    flag: '🇩🇯',
  },
  {
    country: 'Dominica',
    countryCode: 'DM',
    currencyCode: 'XCD',
    currencySign: '$',
    callingCode: '1767',
    flag: '🇩🇲',
  },
  {
    country: 'Dominican Republic',
    countryCode: 'DO',
    currencyCode: 'DOP',
    currencySign: 'RD$',
    callingCode: '1809',
    flag: '🇩🇴',
  },
  {
    country: 'East Timor',
    countryCode: 'TL',
    currencyCode: 'USD',
    currencySign: '$',
    callingCode: '670',
    flag: '🇹🇱',
  },
  {
    country: 'Ecuador',
    countryCode: 'EC',
    currencyCode: 'USD',
    currencySign: '$',
    callingCode: '593',
    flag: '🇪🇨',
  },
  {
    country: 'Egypt',
    countryCode: 'EG',
    currencyCode: 'EGP',
    currencySign: '£',
    callingCode: '20',
    flag: '🇪🇬',
  },
  {
    country: 'El Salvador',
    countryCode: 'SV',
    currencyCode: 'USD',
    currencySign: '$',
    callingCode: '503',
    flag: '🇸🇻',
  },
  {
    country: 'Equatorial Guinea',
    countryCode: 'GQ',
    currencyCode: 'XAF',
    currencySign: 'Fr',
    callingCode: '240',
    flag: '🇬🇶',
  },
  {
    country: 'Eritrea',
    countryCode: 'ER',
    currencyCode: 'ERN',
    currencySign: 'Nfk',
    callingCode: '291',
    flag: '🇪🇷',
  },
  {
    country: 'Estonia',
    countryCode: 'EE',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '372',
    flag: '🇪🇪',
  },
  {
    country: 'Eswatini',
    countryCode: 'SZ',
    currencyCode: 'SZL',
    currencySign: 'L',
    callingCode: '268',
    flag: '🇸🇿',
  },
  {
    country: 'Ethiopia',
    countryCode: 'ET',
    currencyCode: 'ETB',
    currencySign: 'Br',
    callingCode: '251',
    flag: '🇪🇹',
  },
  {
    country: 'Fiji',
    countryCode: 'FJ',
    currencyCode: 'FJD',
    currencySign: '$',
    callingCode: '679',
    flag: '🇫🇯',
  },
  {
    country: 'Finland',
    countryCode: 'FI',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '358',
    flag: '🇫🇮',
  },
  {
    country: 'France',
    countryCode: 'FR',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '33',
    flag: '🇫🇷',
  },
  {
    country: 'Gabon',
    countryCode: 'GA',
    currencyCode: 'XAF',
    currencySign: 'Fr',
    callingCode: '241',
    flag: '🇲🇬',
  },
  {
    country: 'Gambia',
    countryCode: 'GM',
    currencyCode: 'GMD',
    currencySign: 'D',
    callingCode: '220',
    flag: '🇲🇬',
  },
  {
    country: 'Georgia',
    countryCode: 'GE',
    currencyCode: 'GEL',
    currencySign: '₾',
    callingCode: '995',
    flag: '🇬🇪',
  },
  {
    country: 'Germany',
    countryCode: 'DE',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '49',
    flag: '🇩🇪',
  },
  {
    country: 'Ghana',
    countryCode: 'GH',
    currencyCode: 'GHS',
    currencySign: '₵',
    callingCode: '233',
    flag: '🇬🇭',
  },
  {
    country: 'Greece',
    countryCode: 'GR',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '30',
    flag: '🇬🇷',
  },
  {
    country: 'Grenada',
    countryCode: 'GD',
    currencyCode: 'XCD',
    currencySign: '$',
    callingCode: '1473',
    flag: '🇬🇩',
  },
  {
    country: 'Guatemala',
    countryCode: 'GT',
    currencyCode: 'GTQ',
    currencySign: 'Q',
    callingCode: '502',
    flag: '🇲🇽',
  },
  {
    country: 'Guinea',
    countryCode: 'GN',
    currencyCode: 'GNF',
    currencySign: 'Fr',
    callingCode: '224',
    flag: '🇬🇳',
  },
  {
    country: 'Guinea-Bissau',
    countryCode: 'GW',
    currencyCode: 'XOF',
    currencySign: 'Fr',
    callingCode: '245',
    flag: '🇬🇳',
  },
  {
    country: 'Guyana',
    countryCode: 'GY',
    currencyCode: 'GYD',
    currencySign: '$',
    callingCode: '592',
    flag: '🇬🇾',
  },
  {
    country: 'Haiti',
    countryCode: 'HT',
    currencyCode: 'HTG',
    currencySign: 'G',
    callingCode: '509',
    flag: '🇭🇹',
  },
  {
    country: 'Honduras',
    countryCode: 'HN',
    currencyCode: 'HNL',
    currencySign: 'L',
    callingCode: '504',
    flag: '🇭🇳',
  },
  {
    country: 'Hungary',
    countryCode: 'HU',
    currencyCode: 'HUF',
    currencySign: 'Ft',
    callingCode: '36',
    flag: '🇭🇺',
  },
  {
    country: 'Iceland',
    countryCode: 'IS',
    currencyCode: 'ISK',
    currencySign: 'kr',
    callingCode: '354',
    flag: '🇮🇸',
  },
  {
    country: 'India',
    countryCode: 'IN',
    currencyCode: 'INR',
    currencySign: '₹',
    callingCode: '91',
    flag: '🇮🇳',
  },
  {
    country: 'Indonesia',
    countryCode: 'ID',
    currencyCode: 'IDR',
    currencySign: 'Rp',
    callingCode: '62',
    flag: '🇮🇩',
  },
  {
    country: 'Iran',
    countryCode: 'IR',
    currencyCode: 'IRR',
    currencySign: '﷼',
    callingCode: '98',
    flag: '🇮🇷',
  },
  {
    country: 'Iraq',
    countryCode: 'IQ',
    currencyCode: 'IQD',
    currencySign: 'ع.د',
    callingCode: '964',
    flag: '🇮🇶',
  },
  {
    country: 'Ireland',
    countryCode: 'IE',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '353',
    flag: '🇮🇪',
  },
  {
    country: 'Israel',
    countryCode: 'IL',
    currencyCode: 'ILS',
    currencySign: '₪',
    callingCode: '972',
    flag: '🇮🇱',
  },
  {
    country: 'Italy',
    countryCode: 'IT',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '39',
    flag: '🇮🇹',
  },
  {
    country: 'Jamaica',
    countryCode: 'JM',
    currencyCode: 'JMD',
    currencySign: '$',
    callingCode: '1876',
    flag: '🇯🇲',
  },
  {
    country: 'Japan',
    countryCode: 'JP',
    currencyCode: 'JPY',
    currencySign: '¥',
    callingCode: '81',
    flag: '🇯🇵',
  },
  {
    country: 'Jordan',
    countryCode: 'JO',
    currencyCode: 'JOD',
    currencySign: 'د.أ',
    callingCode: '962',
    flag: '🇯🇴',
  },
  {
    country: 'Kazakhstan',
    countryCode: 'KZ',
    currencyCode: 'KZT',
    currencySign: '₸',
    callingCode: '7',
    flag: '🇰🇿',
  },
  {
    country: 'Kenya',
    countryCode: 'KE',
    currencyCode: 'KES',
    currencySign: 'KSh',
    callingCode: '254',
    flag: '🇰🇪',
  },
  {
    country: 'Kiribati',
    countryCode: 'KI',
    currencyCode: 'AUD',
    currencySign: '$',
    callingCode: '686',
    flag: '🇰🇮',
  },
  {
    country: 'Korea, North',
    countryCode: 'KP',
    currencyCode: 'KPW',
    currencySign: '₩',
    callingCode: '850',
    flag: '🇰🇵',
  },
  {
    country: 'Korea, South',
    countryCode: 'KR',
    currencyCode: 'KRW',
    currencySign: '₩',
    callingCode: '82',
    flag: '🇰🇷',
  },
  {
    country: 'Kuwait',
    countryCode: 'KW',
    currencyCode: 'KWD',
    currencySign: 'د.ك',
    callingCode: '965',
    flag: '🇰🇼',
  },
  {
    country: 'Kyrgyzstan',
    countryCode: 'KG',
    currencyCode: 'KGS',
    currencySign: 'лв',
    callingCode: '996',
    flag: '🇰🇬',
  },
  {
    country: 'Laos',
    countryCode: 'LA',
    currencyCode: 'LAK',
    currencySign: '₭',
    callingCode: '856',
    flag: '🇱🇦',
  },
  {
    country: 'Latvia',
    countryCode: 'LV',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '371',
    flag: '🇱🇻',
  },
  {
    country: 'Lebanon',
    countryCode: 'LB',
    currencyCode: 'LBP',
    currencySign: 'ل.ل',
    callingCode: '961',
    flag: '🇱🇧',
  },
  {
    country: 'Lesotho',
    countryCode: 'LS',
    currencyCode: 'LSL',
    currencySign: 'L',
    callingCode: '266',
    flag: '🇱🇸',
  },
  {
    country: 'Liberia',
    countryCode: 'LR',
    currencyCode: 'LRD',
    currencySign: '$',
    callingCode: '231',
    flag: '🇱🇸',
  },
  {
    country: 'Libya',
    countryCode: 'LY',
    currencyCode: 'LYD',
    currencySign: 'ل.د',
    callingCode: '218',
    flag: '🇱🇾',
  },
  {
    country: 'Liechtenstein',
    countryCode: 'LI',
    currencyCode: 'CHF',
    currencySign: 'CHF',
    callingCode: '423',
    flag: '🇱🇮',
  },
  {
    country: 'Lithuania',
    countryCode: 'LT',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '370',
    flag: '🇱🇹',
  },
  {
    country: 'Luxembourg',
    countryCode: 'LU',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '352',
    flag: '🇱🇺',
  },
  {
    country: 'Madagascar',
    countryCode: 'MG',
    currencyCode: 'MGA',
    currencySign: 'Ar',
    callingCode: '261',
    flag: '🇲🇬',
  },
  {
    country: 'Malawi',
    countryCode: 'MW',
    currencyCode: 'MWK',
    currencySign: 'MK',
    callingCode: '265',
    flag: '🇲🇼',
  },
  {
    country: 'Malaysia',
    countryCode: 'MY',
    currencyCode: 'MYR',
    currencySign: 'RM',
    callingCode: '60',
    flag: '🇲🇾',
  },
  {
    country: 'Maldives',
    countryCode: 'MV',
    currencyCode: 'MVR',
    currencySign: 'Rf',
    callingCode: '960',
    flag: '🇲🇻',
  },
  {
    country: 'Mali',
    countryCode: 'ML',
    currencyCode: 'XOF',
    currencySign: 'Fr',
    callingCode: '223',
    flag: '🇲🇱',
  },
  {
    country: 'Malta',
    countryCode: 'MT',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '356',
    flag: '🇲🇹',
  },
  {
    country: 'Marshall Islands',
    countryCode: 'MH',
    currencyCode: 'USD',
    currencySign: '$',
    callingCode: '692',
    flag: '🇲🇭',
  },
  {
    country: 'Mauritania',
    countryCode: 'MR',
    currencyCode: 'MRU',
    currencySign: 'UM',
    callingCode: '222',
    flag: '🇲🇷',
  },
  {
    country: 'Mauritius',
    countryCode: 'MU',
    currencyCode: 'MUR',
    currencySign: '₨',
    callingCode: '230',
    flag: '🇲🇺',
  },
  {
    country: 'Mexico',
    countryCode: 'MX',
    currencyCode: 'MXN',
    currencySign: '$',
    callingCode: '52',
    flag: '🇲🇽',
  },
  {
    country: 'Micronesia',
    countryCode: 'FM',
    currencyCode: 'USD',
    currencySign: '$',
    callingCode: '691',
    flag: '🇫🇲',
  },
  {
    country: 'Moldova',
    countryCode: 'MD',
    currencyCode: 'MDL',
    currencySign: 'lei',
    callingCode: '373',
    flag: '🇲🇩',
  },
  {
    country: 'Monaco',
    countryCode: 'MC',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '377',
    flag: '🇲🇨',
  },
  {
    country: 'Mongolia',
    countryCode: 'MN',
    currencyCode: 'MNT',
    currencySign: '₮',
    callingCode: '976',
    flag: '🇲🇳',
  },
  {
    country: 'Montenegro',
    countryCode: 'ME',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '382',
    flag: '🇲🇪',
  },
  {
    country: 'Morocco',
    countryCode: 'MA',
    currencyCode: 'MAD',
    currencySign: 'د.م.',
    callingCode: '212',
    flag: '🇲🇦',
  },
  {
    country: 'Mozambique',
    countryCode: 'MZ',
    currencyCode: 'MZN',
    currencySign: 'MT',
    callingCode: '258',
    flag: '🇲🇿',
  },
  {
    country: 'Myanmar',
    countryCode: 'MM',
    currencyCode: 'MMK',
    currencySign: 'Ks',
    callingCode: '95',
    flag: '🇲🇲',
  },
  {
    country: 'Namibia',
    countryCode: 'NA',
    currencyCode: 'NAD',
    currencySign: '$',
    callingCode: '264',
    flag: '🇳🇦',
  },
  {
    country: 'Nauru',
    countryCode: 'NR',
    currencyCode: 'AUD',
    currencySign: '$',
    callingCode: '674',
    flag: '🇳🇷',
  },
  {
    country: 'Nepal',
    countryCode: 'NP',
    currencyCode: 'NPR',
    currencySign: 'Rs',
    callingCode: '977',
    flag: '🇳🇵',
  },
  {
    country: 'Netherlands',
    countryCode: 'NL',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '31',
    flag: '🇳🇱',
  },
  {
    country: 'New Caledonia',
    countryCode: 'NC',
    currencyCode: 'XPF',
    currencySign: 'Fr',
    callingCode: '687',
    flag: '🇳🇨',
  },
  {
    country: 'New Zealand',
    countryCode: 'NZ',
    currencyCode: 'NZD',
    currencySign: '$',
    callingCode: '64',
    flag: '🇳🇿',
  },
  {
    country: 'Nicaragua',
    countryCode: 'NI',
    currencyCode: 'NIO',
    currencySign: 'C$',
    callingCode: '505',
    flag: '🇳🇮',
  },
  {
    country: 'Niger',
    countryCode: 'NE',
    currencyCode: 'XOF',
    currencySign: 'Fr',
    callingCode: '227',
    flag: '🇳🇪',
  },
  {
    country: 'Nigeria',
    countryCode: 'NG',
    currencyCode: 'NGN',
    currencySign: '₦',
    callingCode: '234',
    flag: '🇳🇬',
  },
  {
    country: 'Niue',
    countryCode: 'NU',
    currencyCode: 'NZD',
    currencySign: '$',
    callingCode: '683',
    flag: '🇳🇺',
  },
  {
    country: 'Norfolk Island',
    countryCode: 'NF',
    currencyCode: 'AUD',
    currencySign: '$',
    callingCode: '672',
    flag: '🇳🇫',
  },
  {
    country: 'North Macedonia',
    countryCode: 'MK',
    currencyCode: 'MKD',
    currencySign: 'ден',
    callingCode: '389',
    flag: '🇲🇰',
  },
  {
    country: 'Northern Mariana Islands',
    countryCode: 'MP',
    currencyCode: 'USD',
    currencySign: '$',
    callingCode: '1670',
    flag: '🇲🇵',
  },
  {
    country: 'Norway',
    countryCode: 'NO',
    currencyCode: 'NOK',
    currencySign: 'kr',
    callingCode: '47',
    flag: '🇳🇴',
  },
  {
    country: 'Oman',
    countryCode: 'OM',
    currencyCode: 'OMR',
    currencySign: 'ر.ع.',
    callingCode: '968',
    flag: '🇴🇲',
  },
  {
    country: 'Pakistan',
    countryCode: 'PK',
    currencyCode: 'PKR',
    currencySign: 'Rs',
    callingCode: '92',
    flag: '🇵🇰',
  },
  {
    country: 'Palau',
    countryCode: 'PW',
    currencyCode: 'USD',
    currencySign: '$',
    callingCode: '680',
    flag: '🇵🇼',
  },
  {
    country: 'Palestine',
    countryCode: 'PS',
    currencyCode: 'ILS',
    currencySign: '₪',
    callingCode: '970',
    flag: '🇵🇸',
  },
  {
    country: 'Panama',
    countryCode: 'PA',
    currencyCode: 'PAB',
    currencySign: 'B/.',
    callingCode: '507',
    flag: '🇵🇦',
  },
  {
    country: 'Papua New Guinea',
    countryCode: 'PG',
    currencyCode: 'PGK',
    currencySign: 'K',
    callingCode: '675',
    flag: '🇵🇬',
  },
  {
    country: 'Paraguay',
    countryCode: 'PY',
    currencyCode: 'PYG',
    currencySign: '₲',
    callingCode: '595',
    flag: '🇵🇾',
  },
  {
    country: 'Peru',
    countryCode: 'PE',
    currencyCode: 'PEN',
    currencySign: 'S/.',
    callingCode: '51',
    flag: '🇵🇪',
  },
  {
    country: 'Philippines',
    countryCode: 'PH',
    currencyCode: 'PHP',
    currencySign: '₱',
    callingCode: '63',
    flag: '🇵🇭',
  },
  {
    country: 'Pitcairn Islands',
    countryCode: 'PN',
    currencyCode: 'NZD',
    currencySign: '$',
    callingCode: '870',
    flag: '🇵🇳',
  },
  {
    country: 'Poland',
    countryCode: 'PL',
    currencyCode: 'PLN',
    currencySign: 'zł',
    callingCode: '48',
    flag: '🇵🇱',
  },
  {
    country: 'Portugal',
    countryCode: 'PT',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '351',
    flag: '🇵🇹',
  },
  {
    country: 'Qatar',
    countryCode: 'QA',
    currencyCode: 'QAR',
    currencySign: 'ق.ر',
    callingCode: '974',
    flag: '🇶🇦',
  },
  {
    country: 'Romania',
    countryCode: 'RO',
    currencyCode: 'RON',
    currencySign: 'lei',
    callingCode: '40',
    flag: '🇷🇴',
  },
  {
    country: 'Russia',
    countryCode: 'RU',
    currencyCode: 'RUB',
    currencySign: '₽',
    callingCode: '7',
    flag: '🇷🇺',
  },
  {
    country: 'Rwanda',
    countryCode: 'RW',
    currencyCode: 'RWF',
    currencySign: 'FRw',
    callingCode: '250',
    flag: '🇷🇼',
  },
  {
    country: 'Saint Kitts and Nevis',
    countryCode: 'KN',
    currencyCode: 'XCD',
    currencySign: '$',
    callingCode: '1869',
    flag: '🇰🇳',
  },
  {
    country: 'Saint Lucia',
    countryCode: 'LC',
    currencyCode: 'XCD',
    currencySign: '$',
    callingCode: '1758',
    flag: '🇱🇨',
  },
  {
    country: 'Saint Vincent and the Grenadines',
    countryCode: 'VC',
    currencyCode: 'XCD',
    currencySign: '$',
    callingCode: '1784',
    flag: '🇻🇨',
  },
  {
    country: 'Samoa',
    countryCode: 'WS',
    currencyCode: 'WST',
    currencySign: 'T',
    callingCode: '685',
    flag: '🇼🇸',
  },
  {
    country: 'San Marino',
    countryCode: 'SM',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '378',
    flag: '🇸🇲',
  },
  {
    country: 'Sao Tome and Principe',
    countryCode: 'ST',
    currencyCode: 'STN',
    currencySign: 'Db',
    callingCode: '239',
    flag: '🇱🇸',
  },
  {
    country: 'Saudi Arabia',
    countryCode: 'SA',
    currencyCode: 'SAR',
    currencySign: 'ر.س',
    callingCode: '966',
    flag: '🇸🇦',
  },
  {
    country: 'Senegal',
    countryCode: 'SN',
    currencyCode: 'XOF',
    currencySign: 'Fr',
    callingCode: '221',
    flag: '🇸🇳',
  },
  {
    country: 'Serbia',
    countryCode: 'RS',
    currencyCode: 'RSD',
    currencySign: 'дин.',
    callingCode: '381',
    flag: '🇷🇸',
  },
  {
    country: 'Seychelles',
    countryCode: 'SC',
    currencyCode: 'SCR',
    currencySign: '₨',
    callingCode: '248',
    flag: '🇸🇨',
  },
  {
    country: 'Sierra Leone',
    countryCode: 'SL',
    currencyCode: 'SLL',
    currencySign: 'Le',
    callingCode: '232',
    flag: '🇸🇱',
  },
  {
    country: 'Singapore',
    countryCode: 'SG',
    currencyCode: 'SGD',
    currencySign: '$',
    callingCode: '65',
    flag: '🇸🇬',
  },
  {
    country: 'Sint Maarten',
    countryCode: 'SX',
    currencyCode: 'ANG',
    currencySign: 'ƒ',
    callingCode: '1721',
    flag: '🇸🇽',
  },
  {
    country: 'Slovakia',
    countryCode: 'SK',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '421',
    flag: '🇸🇰',
  },
  {
    country: 'Slovenia',
    countryCode: 'SI',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '386',
    flag: '🇸🇮',
  },
  {
    country: 'Solomon Islands',
    countryCode: 'SB',
    currencyCode: 'SBD',
    currencySign: '$',
    callingCode: '677',
    flag: '🇸🇧',
  },
  {
    country: 'Somalia',
    countryCode: 'SO',
    currencyCode: 'SOS',
    currencySign: 'Sh',
    callingCode: '252',
    flag: '🇸🇴',
  },
  {
    country: 'South Africa',
    countryCode: 'ZA',
    currencyCode: 'ZAR',
    currencySign: 'R',
    callingCode: '27',
    flag: '🇿🇦',
  },
  {
    country: 'South Sudan',
    countryCode: 'SS',
    currencyCode: 'SSP',
    currencySign: '£',
    callingCode: '211',
    flag: '🇸🇸',
  },
  {
    country: 'Spain',
    countryCode: 'ES',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '34',
    flag: '🇪🇸',
  },
  {
    country: 'Sri Lanka',
    countryCode: 'LK',
    currencyCode: 'LKR',
    currencySign: 'Rs',
    callingCode: '94',
    flag: '🇱🇰',
  },
  {
    country: 'Sudan',
    countryCode: 'SD',
    currencyCode: 'SDG',
    currencySign: 'ج.س.',
    callingCode: '249',
    flag: '🇸🇩',
  },
  {
    country: 'Suriname',
    countryCode: 'SR',
    currencyCode: 'SRD',
    currencySign: '$',
    callingCode: '597',
    flag: '🇸🇷',
  },
  {
    country: 'Sweden',
    countryCode: 'SE',
    currencyCode: 'SEK',
    currencySign: 'kr',
    callingCode: '46',
    flag: '🇸🇪',
  },
  {
    country: 'Switzerland',
    countryCode: 'CH',
    currencyCode: 'CHF',
    currencySign: 'CHF',
    callingCode: '41',
    flag: '🇨🇭',
  },
  {
    country: 'Syria',
    countryCode: 'SY',
    currencyCode: 'SYP',
    currencySign: 'ل.س',
    callingCode: '963',
    flag: '🇸🇾',
  },
  {
    country: 'Taiwan',
    countryCode: 'TW',
    currencyCode: 'TWD',
    currencySign: 'NT$',
    callingCode: '886',
    flag: '🇹🇼',
  },
  {
    country: 'Tajikistan',
    countryCode: 'TJ',
    currencyCode: 'TJS',
    currencySign: 'ЅМ',
    callingCode: '992',
    flag: '🇹🇯',
  },
  {
    country: 'Tanzania',
    countryCode: 'TZ',
    currencyCode: 'TZS',
    currencySign: 'TSh',
    callingCode: '255',
    flag: '🇹🇿',
  },
  {
    country: 'Thailand',
    countryCode: 'TH',
    currencyCode: 'THB',
    currencySign: '฿',
    callingCode: '66',
    flag: '🇹🇭',
  },
  {
    country: 'Timor-Leste',
    countryCode: 'TL',
    currencyCode: 'USD',
    currencySign: '$',
    callingCode: '670',
    flag: '🇹🇱',
  },
  {
    country: 'Togo',
    countryCode: 'TG',
    currencyCode: 'XOF',
    currencySign: 'Fr',
    callingCode: '228',
    flag: '🇹🇬',
  },
  {
    country: 'Tonga',
    countryCode: 'TO',
    currencyCode: 'TOP',
    currencySign: 'T$',
    callingCode: '676',
    flag: '🇹🇴',
  },
  {
    country: 'Trinidad and Tobago',
    countryCode: 'TT',
    currencyCode: 'TTD',
    currencySign: '$',
    callingCode: '1868',
    flag: '🇹🇹',
  },
  {
    country: 'Tunisia',
    countryCode: 'TN',
    currencyCode: 'TND',
    currencySign: 'د.ت',
    callingCode: '216',
    flag: '🇹🇳',
  },
  {
    country: 'Turkey',
    countryCode: 'TR',
    currencyCode: 'TRY',
    currencySign: '₺',
    callingCode: '90',
    flag: '🇹🇷',
  },
  {
    country: 'Turkmenistan',
    countryCode: 'TM',
    currencyCode: 'TMT',
    currencySign: 'T',
    callingCode: '993',
    flag: '🇹🇲',
  },
  {
    country: 'Tuvalu',
    countryCode: 'TV',
    currencyCode: 'AUD',
    currencySign: '$',
    callingCode: '688',
    flag: '🇹🇻',
  },
  {
    country: 'Uganda',
    countryCode: 'UG',
    currencyCode: 'UGX',
    currencySign: 'USh',
    callingCode: '256',
    flag: '🇺🇬',
  },
  {
    country: 'Ukraine',
    countryCode: 'UA',
    currencyCode: 'UAH',
    currencySign: '₴',
    callingCode: '380',
    flag: '🇺🇦',
  },
  {
    country: 'United Arab Emirates',
    countryCode: 'AE',
    currencyCode: 'AED',
    currencySign: 'د.إ',
    callingCode: '971',
    flag: '🇦🇪',
  },
  {
    country: 'United Kingdom',
    countryCode: 'GB',
    currencyCode: 'GBP',
    currencySign: '£',
    callingCode: '44',
    flag: '🇬🇧',
  },
  {
    country: 'United States',
    countryCode: 'US',
    currencyCode: 'USD',
    currencySign: '$',
    callingCode: '1',
    flag: '🇺🇸',
  },
  {
    country: 'Uruguay',
    countryCode: 'UY',
    currencyCode: 'UYU',
    currencySign: '$',
    callingCode: '598',
    flag: '🇺🇾',
  },
  {
    country: 'Uzbekistan',
    countryCode: 'UZ',
    currencyCode: 'UZS',
    currencySign: 'лв',
    callingCode: '998',
    flag: '🇺🇿',
  },
  {
    country: 'Vanuatu',
    countryCode: 'VU',
    currencyCode: 'VUV',
    currencySign: 'VT',
    callingCode: '678',
    flag: '🇻🇺',
  },
  {
    country: 'Vatican City',
    countryCode: 'VA',
    currencyCode: 'EUR',
    currencySign: '€',
    callingCode: '39',
    flag: '🇻🇦',
  },
  {
    country: 'Venezuela',
    countryCode: 'VE',
    currencyCode: 'VES',
    currencySign: 'Bs.S',
    callingCode: '58',
    flag: '🇻🇪',
  },
  {
    country: 'Vietnam',
    countryCode: 'VN',
    currencyCode: 'VND',
    currencySign: '₫',
    callingCode: '84',
    flag: '🇻🇳',
  },
  {
    country: 'Yemen',
    countryCode: 'YE',
    currencyCode: 'YER',
    currencySign: '﷼',
    callingCode: '967',
    flag: '🇾🇪',
  },
  {
    country: 'Zambia',
    countryCode: 'ZM',
    currencyCode: 'ZMW',
    currencySign: 'ZK',
    callingCode: '260',
    flag: '🇿🇲',
  },
  {
    country: 'Zimbabwe',
    countryCode: 'ZW',
    currencyCode: 'ZWL',
    currencySign: 'Z$',
    callingCode: '263',
    flag: '🇿🇼',
  },
];
